-- =========================================================
-- JOBLINK - SUPABASE / POSTGRESQL SCHEMA
-- Chay file nay trong Supabase SQL Editor hoac bang Supabase CLI.
-- =========================================================

CREATE EXTENSION IF NOT EXISTS pg_trgm;

DO $$
BEGIN
  CREATE TYPE user_role AS ENUM ('admin', 'company', 'candidate');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE user_status AS ENUM ('active', 'pending', 'banned');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE company_status AS ENUM ('pending', 'approved', 'rejected');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE gender_type AS ENUM ('male', 'female', 'other');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE job_type AS ENUM ('full-time', 'part-time', 'internship', 'remote');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE job_status AS ENUM ('active', 'closed', 'expired');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE application_status AS ENUM ('pending', 'reviewing', 'interview', 'accepted', 'rejected');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE payment_status AS ENUM ('pending', 'completed', 'failed', 'refunded');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE payment_method AS ENUM ('bank_transfer', 'momo', 'demo');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE subscription_status AS ENUM ('active', 'expired', 'cancelled');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TABLE IF NOT EXISTS users (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email VARCHAR(150) UNIQUE,
  password VARCHAR(255),
  role user_role NOT NULL,
  status user_status NOT NULL DEFAULT 'active',
  terms_accepted_at TIMESTAMPTZ,
  terms_version VARCHAR(20),
  oauth_provider VARCHAR(20),
  oauth_id VARCHAR(100),
  display_name VARCHAR(150),
  social_avatar VARCHAR(255),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  CONSTRAINT uq_users_oauth UNIQUE (oauth_provider, oauth_id)
);

CREATE TABLE IF NOT EXISTS password_reset_tokens (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  token_hash CHAR(64) NOT NULL UNIQUE,
  expires_at TIMESTAMPTZ NOT NULL,
  used_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_password_reset_user ON password_reset_tokens(user_id);
CREATE INDEX IF NOT EXISTS idx_password_reset_expiry ON password_reset_tokens(expires_at);

CREATE TABLE IF NOT EXISTS categories (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(100) NOT NULL UNIQUE,
  slug VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS companies (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  company_name VARCHAR(200) NOT NULL,
  tax_code VARCHAR(50),
  description TEXT,
  logo_url VARCHAR(255),
  website VARCHAR(255),
  address VARCHAR(255),
  scale VARCHAR(50),
  status company_status NOT NULL DEFAULT 'pending',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS candidates (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  full_name VARCHAR(150) NOT NULL,
  phone VARCHAR(20),
  address VARCHAR(255),
  birth_date DATE,
  gender gender_type,
  skills TEXT,
  experience TEXT,
  education TEXT,
  cv_url VARCHAR(255),
  avatar_url VARCHAR(255),
  is_searchable BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS jobs (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id INTEGER NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  category_id INTEGER REFERENCES categories(id) ON DELETE SET NULL,
  title VARCHAR(200) NOT NULL,
  description TEXT NOT NULL,
  requirements TEXT,
  benefits TEXT,
  salary_min INTEGER,
  salary_max INTEGER,
  salary_negotiable BOOLEAN NOT NULL DEFAULT FALSE,
  location VARCHAR(255),
  job_type job_type NOT NULL DEFAULT 'full-time',
  experience_level VARCHAR(100),
  vacancies INTEGER NOT NULL DEFAULT 1,
  deadline DATE,
  status job_status NOT NULL DEFAULT 'active',
  views INTEGER NOT NULL DEFAULT 0,
  is_vip BOOLEAN NOT NULL DEFAULT FALSE,
  is_featured BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS applications (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  job_id INTEGER NOT NULL REFERENCES jobs(id) ON DELETE CASCADE,
  candidate_id INTEGER NOT NULL REFERENCES candidates(id) ON DELETE CASCADE,
  cv_url VARCHAR(255),
  cover_letter TEXT,
  status application_status NOT NULL DEFAULT 'pending',
  applied_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  CONSTRAINT unique_application UNIQUE (job_id, candidate_id)
);

CREATE TABLE IF NOT EXISTS saved_jobs (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  candidate_id INTEGER NOT NULL REFERENCES candidates(id) ON DELETE CASCADE,
  job_id INTEGER NOT NULL REFERENCES jobs(id) ON DELETE CASCADE,
  saved_at TIMESTAMPTZ DEFAULT NOW(),
  CONSTRAINT unique_save UNIQUE (candidate_id, job_id)
);

CREATE TABLE IF NOT EXISTS packages (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  code VARCHAR(50) NOT NULL UNIQUE,
  price INTEGER NOT NULL DEFAULT 0,
  duration_days INTEGER NOT NULL DEFAULT 30,
  max_job_posts INTEGER NOT NULL DEFAULT 3,
  max_vip_posts INTEGER NOT NULL DEFAULT 0,
  can_search_cv BOOLEAN NOT NULL DEFAULT FALSE,
  max_cv_views INTEGER NOT NULL DEFAULT 0,
  description TEXT,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  sort_order INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS payments (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id INTEGER NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  package_id INTEGER NOT NULL REFERENCES packages(id),
  amount INTEGER NOT NULL,
  status payment_status NOT NULL DEFAULT 'pending',
  payment_method payment_method NOT NULL DEFAULT 'bank_transfer',
  transaction_code VARCHAR(100) UNIQUE,
  expires_at TIMESTAMPTZ,
  terms_accepted_at TIMESTAMPTZ,
  terms_version VARCHAR(20),
  privacy_version VARCHAR(20),
  accepted_ip VARCHAR(64),
  accepted_user_agent VARCHAR(500),
  note TEXT,
  paid_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS company_subscriptions (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id INTEGER NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  package_id INTEGER NOT NULL REFERENCES packages(id),
  payment_id INTEGER REFERENCES payments(id),
  started_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  expires_at TIMESTAMPTZ NOT NULL,
  job_posts_used INTEGER NOT NULL DEFAULT 0,
  vip_posts_used INTEGER NOT NULL DEFAULT 0,
  cv_views_used INTEGER NOT NULL DEFAULT 0,
  status subscription_status NOT NULL DEFAULT 'active'
);

DROP TRIGGER IF EXISTS trg_users_updated_at ON users;
CREATE TRIGGER trg_users_updated_at
BEFORE UPDATE ON users
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_jobs_updated_at ON jobs;
CREATE TRIGGER trg_jobs_updated_at
BEFORE UPDATE ON jobs
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_applications_updated_at ON applications;
CREATE TRIGGER trg_applications_updated_at
BEFORE UPDATE ON applications
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE INDEX IF NOT EXISTS idx_users_role ON users(role);
CREATE INDEX IF NOT EXISTS idx_users_status ON users(status);
CREATE INDEX IF NOT EXISTS idx_companies_user_id ON companies(user_id);
CREATE INDEX IF NOT EXISTS idx_companies_status ON companies(status);
CREATE INDEX IF NOT EXISTS idx_candidates_user_id ON candidates(user_id);
CREATE INDEX IF NOT EXISTS idx_jobs_company_id ON jobs(company_id);
CREATE INDEX IF NOT EXISTS idx_jobs_category_id ON jobs(category_id);
CREATE INDEX IF NOT EXISTS idx_jobs_status_created_at ON jobs(status, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_jobs_location_trgm ON jobs USING GIN (location gin_trgm_ops);
CREATE INDEX IF NOT EXISTS idx_jobs_title_description_fts
  ON jobs USING GIN (to_tsvector('simple', coalesce(title, '') || ' ' || coalesce(description, '')));
CREATE INDEX IF NOT EXISTS idx_applications_job_id ON applications(job_id);
CREATE INDEX IF NOT EXISTS idx_applications_candidate_id ON applications(candidate_id);
CREATE INDEX IF NOT EXISTS idx_saved_jobs_candidate_id ON saved_jobs(candidate_id);
CREATE INDEX IF NOT EXISTS idx_payments_company_id ON payments(company_id);
CREATE INDEX IF NOT EXISTS idx_company_subscriptions_company_id ON company_subscriptions(company_id);

INSERT INTO categories (name, slug) VALUES
  ('Công nghệ thông tin', 'cong-nghe-thong-tin'),
  ('Kinh doanh / Bán hàng', 'kinh-doanh-ban-hang'),
  ('Marketing / Truyền thông', 'marketing-truyen-thong'),
  ('Kế toán / Kiểm toán', 'ke-toan-kiem-toan'),
  ('Nhân sự / Hành chính', 'nhan-su-hanh-chinh'),
  ('Thiết kế / Sáng tạo', 'thiet-ke-sang-tao'),
  ('Chăm sóc khách hàng', 'cham-soc-khach-hang'),
  ('Logistics / Vận tải', 'logistics-van-tai')
ON CONFLICT (slug) DO UPDATE SET name = EXCLUDED.name;

INSERT INTO packages
  (name, code, price, duration_days, max_job_posts, max_vip_posts, can_search_cv, max_cv_views, description, sort_order)
VALUES
  ('Miễn phí', 'free', 0, 30, 3, 0, FALSE, 0, 'Đăng tối đa 3 tin/tháng, không có tin VIP.', 0),
  ('Basic', 'basic', 1500000, 30, 10, 2, TRUE, 10, '10 tin/tháng, 2 tin VIP và 10 lượt xem CV ứng viên.', 1),
  ('Pro', 'pro', 3500000, 30, 30, 10, TRUE, 50, '30 tin/tháng, 10 tin VIP, tìm kiếm 50 CV ứng viên.', 2),
  ('Enterprise', 'enterprise', 8000000, 30, 999, 999, TRUE, 999, 'Không giới hạn tin đăng, tin VIP và xem CV ứng viên.', 3)
ON CONFLICT (code) DO UPDATE SET
  name = EXCLUDED.name,
  price = EXCLUDED.price,
  duration_days = EXCLUDED.duration_days,
  max_job_posts = EXCLUDED.max_job_posts,
  max_vip_posts = EXCLUDED.max_vip_posts,
  can_search_cv = EXCLUDED.can_search_cv,
  max_cv_views = EXCLUDED.max_cv_views,
  description = EXCLUDED.description,
  sort_order = EXCLUDED.sort_order;
