ALTER TABLE applications
  ADD COLUMN IF NOT EXISTS status_note TEXT;

CREATE TABLE IF NOT EXISTS application_status_history (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  application_id INTEGER NOT NULL REFERENCES applications(id) ON DELETE CASCADE,
  from_status application_status NOT NULL,
  to_status application_status NOT NULL,
  note TEXT,
  changed_by_user_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
  changed_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_application_status_history_application
  ON application_status_history(application_id);
